/**
 * PTWebServiceSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.tempuri;

public interface PTWebServiceSoap extends java.rmi.Remote {
    public java.lang.String AT_ModifyLupeGoodSale(org.tempuri.AT_ModifyLupeGoodSaleDt dt, java.lang.String sOLDComp) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalMaxnetronDashboardResponseAT_OrderAutoCalMaxnetronDashboardResult AT_OrderAutoCalMaxnetronDashboard(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalCastrolDashboardResponseAT_OrderAutoCalCastrolDashboardResult AT_OrderAutoCalCastrolDashboard(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeBrnNotSetResponseAT_GetLupeBrnNotSetResult AT_GetLupeBrnNotSet() throws java.rmi.RemoteException;
    public java.lang.String AT_SetlupeLPG(java.lang.String lpgCode, java.lang.String oilCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetBrNameCodeLupeResponseAT_GetBrNameCodeLupeResult AT_GetBrNameCodeLupe(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalPowerDashboardResponseAT_OrderAutoCalPowerDashboardResult AT_OrderAutoCalPowerDashboard(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName) throws java.rmi.RemoteException;
    public java.lang.String LDAP_VALIDATE_USER(java.lang.String userID) throws java.rmi.RemoteException;
    public java.lang.String LDAP_ResetPassword(java.lang.String userID, java.lang.String oldPassword, java.lang.String newPassword) throws java.rmi.RemoteException;
    public org.tempuri.ActionResult PTHR_EmployeeDataInsert(java.lang.String empcode_creator, org.tempuri.Pthr_EmployeeDataObj pthrEmpObj, org.tempuri.Ptref_EmpObj ptrefEmpObj) throws java.rmi.RemoteException;
    public org.tempuri.ActionResult PTHR_EmployeeDataUpdate(java.lang.String empcode_modifier, org.tempuri.Pthr_EmployeeDataObj pthrEmpObj, org.tempuri.Ptref_EmpObj ptrefEmpObj) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetFinanceResponseSupply_GetFinanceResult supply_GetFinance(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sDate) throws java.rmi.RemoteException;
    public boolean supply_UpdateAdjust(org.tempuri.Supply_UpdateAdjustDst dst, java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sDate) throws java.rmi.RemoteException;
    public java.lang.String setupLoan(java.lang.String jsonText) throws java.rmi.RemoteException;
    public java.lang.String cancelSetupLoan(java.lang.String jsonText) throws java.rmi.RemoteException;
    public java.lang.String validateLoan(java.lang.String jsonText) throws java.rmi.RemoteException;
    public java.lang.String updateInfPaymentSuccess(java.lang.String flag, java.lang.String inBrn, java.lang.String inNo) throws java.rmi.RemoteException;
    public java.lang.String updateInfPaymentFailed(java.lang.String remark, java.lang.String inBrn, java.lang.String inNo) throws java.rmi.RemoteException;
    public java.lang.String PUN_SELL_GET_GL_DATA(java.lang.String punSellDataInterfaceAxJSON) throws java.rmi.RemoteException;
    public java.lang.String PUN_BUY_GET_GL_DATA(java.lang.String punBuyDataInterfaceAxJSON, java.lang.String countListPun, java.lang.String countDoc, java.lang.String payeeCode) throws java.rmi.RemoteException;
    public java.lang.String PUN_BUY_InterfaceAX(java.lang.String periodDDMMYYYY, java.lang.String ledgerJournalTransImportJSON, java.lang.String flagVoucher, java.lang.String totalCredit, java.lang.String documentDateLast) throws java.rmi.RemoteException;
    public java.lang.String PUN_SELL_InterfaceAX(java.lang.String periodDDMMYYYY, java.lang.String ledgerJournalTransImportJSON) throws java.rmi.RemoteException;
    public java.lang.String LDAP_GET_ALL_USER() throws java.rmi.RemoteException;
    public java.lang.String LDAP_USER_AUTHEN(java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException;
    public java.lang.String LDAP_HRIS_USER_AUTHEN(java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException;
    public java.lang.String LDAP_FIND_USER_BY_DISPLAYNAME(java.lang.String displayName) throws java.rmi.RemoteException;
    public java.lang.String unitCode_PUN(java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException;
    public java.lang.String AR_PunTaxSale(java.lang.String jsonTextHD, java.lang.String jsonTextDtl) throws java.rmi.RemoteException;
    public boolean AT_CalDayForWebOrder(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sStationbrn, double dRotationPolicy, int iAverageSell, int iAheadago) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetRotationdayResponseAT_GetRotationdayResult AT_GetRotationday(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public java.lang.String AT_EditRotationDay(org.tempuri.AT_EditRotationDayDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetDayAvgSellResponseAT_GetDayAvgSellResult AT_GetDayAvgSell(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public java.lang.String AT_EditDayAvgSell(org.tempuri.AT_EditDayAvgSellDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetdayByBranchResponseAT_GetdayByBranchResult AT_GetdayByBranch(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetdayByBranchLPGResponseAT_GetdayByBranchLPGResult AT_GetdayByBranchLPG(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public java.lang.String AT_EditDayByBranch(org.tempuri.AT_EditDayByBranchDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public java.lang.String AT_EditDayByBranchLPG(org.tempuri.AT_EditDayByBranchLPGDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertDayByBranchLPG(org.tempuri.AT_InsertDayByBranchLPGDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetBrNameCodeResponseAT_GetBrNameCodeResult AT_GetBrNameCode(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLPGBrNameCodeResponseAT_GetLPGBrNameCodeResult AT_GetLPGBrNameCode() throws java.rmi.RemoteException;
    public org.tempuri.AT_LPGListResponseAT_LPGListResult AT_LPGList() throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalLPGResponseAT_OrderAutoCalLPGResult AT_OrderAutoCalLPG(int iTYPE) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertCompleteCalcLPG(java.lang.String sOLDComp, java.lang.String sDepotBrn, org.tempuri.AT_InsertCompleteCalcLPGODTB oDTB, java.lang.String sFileName) throws java.rmi.RemoteException;
    public org.tempuri.AT_BrowseAutoCalLPGResponseAT_BrowseAutoCalLPGResult AT_BrowseAutoCalLPG(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sStatus) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationLPGResponseAT_PrintToStationLPGResult AT_PrintToStationLPG(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate) throws java.rmi.RemoteException;
    public boolean AT_CreateNewWebOrderLPG(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.util.Calendar dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalMaxnetronResponseAT_OrderAutoCalMaxnetronResult AT_OrderAutoCalMaxnetron(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalPowerJetResponseAT_OrderAutoCalPowerJetResult AT_OrderAutoCalPowerJet(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetBrnLupeConfigResponseAT_GetBrnLupeConfigResult AT_GetBrnLupeConfig(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String brnCode, java.lang.String sCommand) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeNameCodeResponseAT_GetLupeNameCodeResult AT_GetLupeNameCode(java.lang.String sCode) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertAutoLupe(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String brnCode, java.lang.String brnName, java.lang.String lupeCode, java.lang.String lupeName, java.lang.String lupeType, java.lang.String sCmd) throws java.rmi.RemoteException;
    public java.lang.String AT_ModifyAutoLupe(org.tempuri.AT_ModifyAutoLupeDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBranch) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeNameCodeForEditResponseAT_GetLupeNameCodeForEditResult AT_GetLupeNameCodeForEdit(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sCode) throws java.rmi.RemoteException;
    public java.lang.String AT_ModifyAutoLupeDepot(org.tempuri.AT_ModifyAutoLupeDepotDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalCastrolResponseAT_OrderAutoCalCastrolResult AT_OrderAutoCalCastrol(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sType) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertCompleteCalcCastrol(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcCastrolODTB oDTB, java.lang.String sFileName) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertCompleteCalcPowerJet(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcPowerJetODTB oDTB, java.lang.String sFileName) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertCompleteCalcMaxnetron(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcMaxnetronODTB oDTB, java.lang.String sFileName, java.lang.String sVenderCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationConResponseAT_PrintToStationConResult AT_PrintToStationCon(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationLPGConResponseAT_PrintToStationLPGConResult AT_PrintToStationLPGCon(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationCastrolConResponseAT_PrintToStationCastrolConResult AT_PrintToStationCastrolCon(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate, java.lang.String sVendor) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationCastrolSAPResponseAT_PrintToStationCastrolSAPResult AT_PrintToStationCastrolSAP(org.tempuri.AT_PrintToStationCastrolSAPODTB oDTB, java.lang.String sType, java.lang.String ptBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationPowerJetConResponseAT_PrintToStationPowerJetConResult AT_PrintToStationPowerJetCon(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate, java.lang.String sVendor) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationPowerJetSAPResponseAT_PrintToStationPowerJetSAPResult AT_PrintToStationPowerJetSAP(org.tempuri.AT_PrintToStationPowerJetSAPODTB oDTB, java.lang.String sType, java.lang.String ptBrn) throws java.rmi.RemoteException;
    public java.lang.String AT_TestToStag(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationMaxnetronConResponseAT_PrintToStationMaxnetronConResult AT_PrintToStationMaxnetronCon(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationMaxnetronSAPResponseAT_PrintToStationMaxnetronSAPResult AT_PrintToStationMaxnetronSAP(org.tempuri.AT_PrintToStationMaxnetronSAPODTB oDTB, java.lang.String sType, java.lang.String ptBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcPrintResponseAT_InsertCompleteCalcPrintResult AT_InsertCompleteCalcPrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, org.tempuri.AT_InsertCompleteCalcPrintODTB oDTB, java.lang.String sFileName, java.lang.String sBrnName) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcLPGPrintResponseAT_InsertCompleteCalcLPGPrintResult AT_InsertCompleteCalcLPGPrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, org.tempuri.AT_InsertCompleteCalcLPGPrintODTB oDTB, java.lang.String sFileName) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcPowerJetPrintResponseAT_InsertCompleteCalcPowerJetPrintResult AT_InsertCompleteCalcPowerJetPrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcPowerJetPrintODTB oDTB, java.lang.String sFileName, java.lang.String sVendorCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcCastrolPrintResponseAT_InsertCompleteCalcCastrolPrintResult AT_InsertCompleteCalcCastrolPrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcCastrolPrintODTB oDTB, java.lang.String sFileName, java.lang.String sVendorCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcMaxnetronPrintResponseAT_InsertCompleteCalcMaxnetronPrintResult AT_InsertCompleteCalcMaxnetronPrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcMaxnetronPrintODTB oDTB, java.lang.String sFileName, java.lang.String sVenderCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeMasterResponseAT_GetLupeMasterResult AT_GetLupeMaster() throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalReviseResponseAT_OrderAutoCalReviseResult AT_OrderAutoCalRevise(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_InsertCompleteCalcRevisePrintResponseAT_InsertCompleteCalcRevisePrintResult AT_InsertCompleteCalcRevisePrint(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sDepotBrnName, org.tempuri.AT_InsertCompleteCalcRevisePrintODTB oDTB, java.lang.String sFileName, java.lang.String sVendorCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationReviseSAPResponseAT_PrintToStationReviseSAPResult AT_PrintToStationReviseSAP(org.tempuri.AT_PrintToStationReviseSAPODTB oDTB, java.lang.String sType, java.lang.String ptBrn) throws java.rmi.RemoteException;
    public java.lang.String AT_GetLupeMaxType() throws java.rmi.RemoteException;
    public java.lang.String AT_AddLupeMaster(java.lang.String sLupeCode, java.lang.String sLupeName, java.lang.String sCode, java.lang.String sName) throws java.rmi.RemoteException;
    public java.lang.String AT_DeleteLupeMaster(java.lang.String sLupeCode, java.lang.String sCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeNameCodeForEditBResponseAT_GetLupeNameCodeForEditBResult AT_GetLupeNameCodeForEditB(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeNameCodeOtherResponseAT_GetLupeNameCodeOtherResult AT_GetLupeNameCodeOther(java.lang.String sCode) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetBrnLupeConfigOtherResponseAT_GetBrnLupeConfigOtherResult AT_GetBrnLupeConfigOther(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String brnCode, java.lang.String sLupecode) throws java.rmi.RemoteException;
    public java.lang.String AT_EditDayTransfer(org.tempuri.AT_EditDayTransferDt dt, java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetDayTransferResponseAT_GetDayTransferResult AT_GetDayTransfer(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalCastrolSplitResponseAT_OrderAutoCalCastrolSplitResult AT_OrderAutoCalCastrolSplit(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBrnGroup, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalMaxnetronSplitResponseAT_OrderAutoCalMaxnetronSplitResult AT_OrderAutoCalMaxnetronSplit(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBrnGroup, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalPowerJetSplitResponseAT_OrderAutoCalPowerJetSplitResult AT_OrderAutoCalPowerJetSplit(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sBrnGroup, java.lang.String sType) throws java.rmi.RemoteException;
    public org.tempuri.AT_InquiryLupeBrnDepotResponseAT_InquiryLupeBrnDepotResult AT_InquiryLupeBrnDepot(java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_GetLupeGoodSaleResponseAT_GetLupeGoodSaleResult AT_GetLupeGoodSale(java.lang.String sCode) throws java.rmi.RemoteException;
    public void mailService1(java.lang.String sTo, java.lang.String sMessage) throws java.rmi.RemoteException;
    public void mailService2(java.lang.String sTo, java.lang.String sSubject, java.lang.String sMessage) throws java.rmi.RemoteException;
    public void mailService3(java.lang.String sFrom, java.lang.String sTo, java.lang.String sSubject, java.lang.String sMessage) throws java.rmi.RemoteException;
    public void mailService4(java.lang.String sServer, java.lang.String sFrom, java.lang.String sTo, java.lang.String sSubject, java.lang.String sMessage) throws java.rmi.RemoteException;
    public void smsService() throws java.rmi.RemoteException;
    public boolean loWrite(java.lang.String sProject, java.util.Calendar dTime, java.lang.String sIp, java.lang.String sUser, java.lang.String sMessage) throws java.rmi.RemoteException;
    public boolean loWritecus(java.lang.String sProject, java.util.Calendar dTime, java.lang.String sIp, java.lang.String sUser) throws java.rmi.RemoteException;
    public org.tempuri.LoReadResponseLoReadResult loRead(java.lang.String sProject, java.util.Calendar dTime) throws java.rmi.RemoteException;
    public org.tempuri.LoReadcusResponseLoReadcusResult loReadcus(java.lang.String sProject, java.util.Calendar dTime) throws java.rmi.RemoteException;
    public boolean arUpdateAging(org.tempuri.ArUpdateAgingDts dts) throws java.rmi.RemoteException;
    public double arCheckLimitAging(java.lang.String sComp, java.lang.String sBrn, java.lang.String sCstno, java.lang.String sType) throws java.rmi.RemoteException;
    public boolean arCheckDisk8(java.lang.String sComp, java.lang.String sBrn, java.lang.String sCstno, java.lang.String sType) throws java.rmi.RemoteException;
    public boolean WO_SetStatus(java.lang.String sOrderNo, int nStatus, java.lang.String sUser) throws java.rmi.RemoteException;
    public int WO_AutoAllowCheck(java.lang.String sOrderNo, double dCustLimit) throws java.rmi.RemoteException;
    public boolean WO_UpdateCenterStatus() throws java.rmi.RemoteException;
    public boolean WO_UpdateCenterStatus_Other() throws java.rmi.RemoteException;
    public double WO_CheckLimitWebOrder(java.lang.String sCstno) throws java.rmi.RemoteException;
    public double WO_CheckLimitWebOrderWithOut(java.lang.String sCstno, java.lang.String sOrdno) throws java.rmi.RemoteException;
    public boolean AN_SuitableCalc(java.lang.String sComp, java.lang.String sBrn) throws java.rmi.RemoteException;
    public boolean AN_SuitableAdjust(java.lang.String sComp, java.lang.String sBrn, int nSEQ) throws java.rmi.RemoteException;
    public boolean AT_VersionControl(java.lang.String sMAC, java.lang.String sUSER, java.lang.String sIP, java.lang.String sVER) throws java.rmi.RemoteException;
    public java.lang.String AT_VersionUpdateCheck(java.lang.String sMAC) throws java.rmi.RemoteException;
    public boolean AT_VersionUpdateComplete(java.lang.String sMAC) throws java.rmi.RemoteException;
    public org.tempuri.AT_DepotListResponseAT_DepotListResult AT_DepotList() throws java.rmi.RemoteException;
    public org.tempuri.AT_GetProductListResponseAT_GetProductListResult AT_GetProductList() throws java.rmi.RemoteException;
    public org.tempuri.AT_StationNotSetLeadTimeResponseAT_StationNotSetLeadTimeResult AT_StationNotSetLeadTime() throws java.rmi.RemoteException;
    public org.tempuri.AT_CustomerNotSetLeadTimeResponseAT_CustomerNotSetLeadTimeResult AT_CustomerNotSetLeadTime() throws java.rmi.RemoteException;
    public org.tempuri.AT_CurrentPolicyResponseAT_CurrentPolicyResult AT_CurrentPolicy(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public boolean AT_LoginLDAP(java.lang.String sUsername, java.lang.String sPassword) throws java.rmi.RemoteException;
    public boolean AT_UpdatePolicy(java.lang.String sDepotComp, java.lang.String sDepotBrn, double dRotateDay, int iDayAvgSell) throws java.rmi.RemoteException;
    public org.tempuri.AT_StationConfigResponseAT_StationConfigResult AT_StationConfig(java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public org.tempuri.AT_ViewAllResponseAT_ViewAllResult AT_ViewAll(java.lang.String sOLDComp) throws java.rmi.RemoteException;
    public boolean AT_InsertStationConfig(org.tempuri.AT_InsertStationConfigODTB oDTB) throws java.rmi.RemoteException;
    public org.tempuri.AT_OrderAutoCalResponseAT_OrderAutoCalResult AT_OrderAutoCal(int iTYPE, java.lang.String sOLDComp, java.lang.String sDepotBrn) throws java.rmi.RemoteException;
    public boolean AT_InsertAutoCalculate(org.tempuri.AT_InsertAutoCalculateODTB oDTB) throws java.rmi.RemoteException;
    public java.lang.String AT_InsertCompleteCalc(java.lang.String sOLDComp, java.lang.String sDepotBrn, org.tempuri.AT_InsertCompleteCalcODTB oDTB, java.lang.String sFileName) throws java.rmi.RemoteException;
    public boolean AT_CreateNewWebOrder(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.util.Calendar dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_BrowseAutoCalResponseAT_BrowseAutoCalResult AT_BrowseAutoCal(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.lang.String sStatus) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationResponseAT_PrintToStationResult AT_PrintToStation(java.lang.String sOLDComp, java.lang.String sDepotBrn, java.util.Calendar dtRPTdate) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationSAPResponseAT_PrintToStationSAPResult AT_PrintToStationSAP(org.tempuri.AT_PrintToStationSAPODTB oDTB) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationSAPNoShipmentResponseAT_PrintToStationSAPNoShipmentResult AT_PrintToStationSAPNoShipment(org.tempuri.AT_PrintToStationSAPNoShipmentODTB oDTB) throws java.rmi.RemoteException;
    public org.tempuri.AT_PrintToStationSAPLPGResponseAT_PrintToStationSAPLPGResult AT_PrintToStationSAPLPG(org.tempuri.AT_PrintToStationSAPLPGODTB oDTB) throws java.rmi.RemoteException;
    public boolean AN_MovePreOrder2Order(java.lang.String sComp, java.lang.String sBrn, int nSEQ, int nOrderStatus) throws java.rmi.RemoteException;
    public boolean AN_MovePreOrder2Order_Split(java.lang.String sComp, java.lang.String sBrn, int nSEQ, int nOrderStatus) throws java.rmi.RemoteException;
    public boolean AN_UpdateOrderSplitNo() throws java.rmi.RemoteException;
    public org.tempuri.WebStationGetLotusResponseWebStationGetLotusResult webStationGetLotus(java.lang.String comp, java.lang.String brn, java.lang.String stkdate) throws java.rmi.RemoteException;
    public boolean WO_ReGenerateOthOrder() throws java.rmi.RemoteException;
    public java.lang.String GPS_SendDriver(java.lang.String sDrcomp, java.lang.String sDrno) throws java.rmi.RemoteException;
    public java.lang.String GPS_SendTruck(java.lang.String sTrcomp, java.lang.String sTrno) throws java.rmi.RemoteException;
    public java.lang.String GPS_SendSite(java.lang.String sStcomp, java.lang.String sStno) throws java.rmi.RemoteException;
    public java.lang.String GPS_SendOil() throws java.rmi.RemoteException;
    public java.lang.String GPS_SendJobDr(java.lang.String sJhcomp, java.lang.String sJhbrn, java.lang.String sJhlocation, java.lang.String sJhrunno) throws java.rmi.RemoteException;
    public java.lang.String GPS_GetSiteFromGPS(java.lang.String sStrXml) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetEmployeeDataResponseWSA_GetEmployeeDataResult WSA_GetEmployeeData(java.lang.String sEmployeeData) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetBranchGroupResponseWSA_GetBranchGroupResult WSA_GetBranchGroup(java.lang.String sEmployeeData) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetSystemDataResponseWSA_GetSystemDataResult WSA_GetSystemData(java.lang.String sEmployeeData, java.lang.String sSystemName) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetSystemNameResponseWSA_GetSystemNameResult WSA_GetSystemName(java.lang.String sEmployeeData) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetBranchDataResponseWSA_GetBranchDataResult WSA_GetBranchData(java.lang.String sEmployeeData, java.lang.String sSystemName, java.lang.String sBranchCode) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetBranchNameResponseWSA_GetBranchNameResult WSA_GetBranchName(java.lang.String sEmployeeData, java.lang.String sSystemName) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetModuleDataResponseWSA_GetModuleDataResult WSA_GetModuleData(java.lang.String sEmployeeData, java.lang.String sSystemName, java.lang.String sModuleName, java.lang.String sPermission) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetModuleNameResponseWSA_GetModuleNameResult WSA_GetModuleName(java.lang.String sEmployeeData, java.lang.String sSystemName, java.lang.String sModuleName) throws java.rmi.RemoteException;
    public org.tempuri.WSA_GetAcessControlResponseWSA_GetAcessControlResult WSA_GetAcessControl(java.lang.String sEmployeeData, java.lang.String sSystemName) throws java.rmi.RemoteException;
    public boolean writeLog(java.lang.String IP, java.lang.String user, java.lang.String sys, java.lang.String event, java.lang.String modname, java.lang.String note) throws java.rmi.RemoteException;
    public org.tempuri.PTG_ProductResponsePTG_ProductResult PTG_Product() throws java.rmi.RemoteException;
    public org.tempuri.POS_PROMOTION_GETResponsePOS_PROMOTION_GETResult POS_PROMOTION_GET(java.lang.String sBRN) throws java.rmi.RemoteException;
    public boolean POS_PROMOTION_MARK(java.lang.String sBRN) throws java.rmi.RemoteException;
    public boolean POS_PROMOTION_SET(org.tempuri.POS_PROMOTION_SETODS oDS) throws java.rmi.RemoteException;
    public org.tempuri.PTG_StationOfDepotResponsePTG_StationOfDepotResult PTG_StationOfDepot(java.lang.String STATION) throws java.rmi.RemoteException;
    public org.tempuri.PTG_AllStationOfDepotResponsePTG_AllStationOfDepotResult PTG_AllStationOfDepot() throws java.rmi.RemoteException;
    public boolean AUTOMATION_ADDDATA(java.lang.String sString) throws java.rmi.RemoteException;
    public boolean PTG_VersionControl(java.lang.String sSystem, java.lang.String sMAC, java.lang.String sUSER, java.lang.String sIP, java.lang.String sVER) throws java.rmi.RemoteException;
    public java.lang.String PTG_VersionUpdateCheck(java.lang.String sSystem, java.lang.String sMAC) throws java.rmi.RemoteException;
    public boolean PTG_VersionUpdateComplete(java.lang.String sSystem, java.lang.String sMAC) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetValueFinanceResponseSupply_GetValueFinanceResult supply_GetValueFinance(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sDate) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetValueOilSupplyResponseSupply_GetValueOilSupplyResult supply_GetValueOilSupply(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sDate) throws java.rmi.RemoteException;
    public boolean supply_SaveToSPfnbals(org.tempuri.Supply_SaveToSPfnbalsODT oDT, java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sDate, java.lang.String sUser) throws java.rmi.RemoteException;
    public org.tempuri.Supply_CheckApMngPRResponseSupply_CheckApMngPRResult supply_CheckApMngPR(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sLocation, java.lang.String sDate) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetDataforProcessResponseSupply_GetDataforProcessResult supply_GetDataforProcess() throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetSuplysiteResponseSupply_GetSuplysiteResult supply_GetSuplysite() throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetForcastValueResponseSupply_GetForcastValueResult supply_GetForcastValue(java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sSupplier, java.lang.String sStDate, java.lang.String sSpDate) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetMrPrFinanceResponseSupply_GetMrPrFinanceResult supply_GetMrPrFinance(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sStDate, java.lang.String sSpDate) throws java.rmi.RemoteException;
    public java.lang.String supply_CheckApPR(java.lang.String sSupplier, java.lang.String sComp, java.lang.String sBrn, java.lang.String sLocation, java.lang.String sDate) throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetAllSupplierResponseSupply_GetAllSupplierResult supply_GetAllSupplier() throws java.rmi.RemoteException;
    public org.tempuri.Supply_GetSupplierResponseSupply_GetSupplierResult supply_GetSupplier(java.lang.String sSpcode, java.lang.String sSpname) throws java.rmi.RemoteException;
}
